theme: jekyll-theme-minimal
logo: img2.jpeg
title: Gabriela Smarelli
description: I am a Ph.D. student at the University of Oxford and my field is labor economics. I am working under the supervision of professors Gabriel Ulyssea and Douglas Gollin. For my CV, reach out to diala.almasri@sjc.ox.ac.uk. #Here is my <a href="CV.pdf">CV</a>.
